apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: main-container
    image: asinatra/flask-app:v1.0.1
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
    env:
    - name: CONTENT
      value: "Test"
    readinessProbe:
      httpGet:
        path: /
        port: 5000
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 20
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 80m
        memory: 128Mi
