apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: team1
spec:
  containers:
  - name: main-container
    image: asinatra/flask-app:v1.0.0
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
