apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.labels }}
  labels:
  {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.labels }}
      labels:
      {{- toYaml .Values.labels | nindent 4 }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}
        ports:
          - name: http
            containerPort: {{ .Values.container.port }}
            protocol: TCP
        {{ if .Values.environment }}
        env:
        {{- range $k, $v := .Values.environment }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }} 
        {{- end }}   
      
      {{ if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{ end }}
